sudo: required

services:
  - docker

git:
  depth: 1

script:
- 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash ./release.sh all push; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./release.sh all; fi'
